a=4
b=5
print("a+b",a+b)
print("a-b",a-b)
print("a*b",a*b)
print("a/b",a/b)
print("a%b",a%b)
print("b%a",b%a)
print("a**b",a**b)
print("a//b",a//b)
print("-a/b",-a/b)
print("-a//b",-a//b)
print("b%a",b%a)